#!/bin/bash

#SBATCH --job-name=unzip        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=1        # Schedule one core
#SBATCH --time=12:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown    # Run on either the Red or Brown queue

# Print out the hostname of the node the job is running on
unzip train.zip
